-- MySQL Script generated by MySQL Workbench
-- Mon Nov  8 11:05:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema batalha
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `batalha` ;

-- -----------------------------------------------------
-- Schema batalha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `batalha` DEFAULT CHARACTER SET utf8 ;
USE `batalha` ;

-- -----------------------------------------------------
-- Table `batalha`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batalha`.`Person` ;

CREATE TABLE IF NOT EXISTS `batalha`.`Person` (
  `nome` VARCHAR(45) NOT NULL,
  `raca` VARCHAR(45) NOT NULL,
  `HP` INT NOT NULL,
  `isPlayable` TINYINT NOT NULL DEFAULT 0,
  `isDead` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`nome`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `batalha`.`Weapon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batalha`.`Weapon` ;

CREATE TABLE IF NOT EXISTS `batalha`.`Weapon` (
  `distance` VARCHAR(1) NOT NULL,
  `dano` INT NOT NULL,
  `Character_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`distance`, `Character_nome`),
  INDEX `fk_Weapon_Character_idx` (`Character_nome` ASC) VISIBLE,
  CONSTRAINT `fk_Weapon_Character`
    FOREIGN KEY (`Character_nome`)
    REFERENCES `batalha`.`Person` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `batalha`.`Alliance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batalha`.`Alliance` ;

CREATE TABLE IF NOT EXISTS `batalha`.`Alliance` (
  `lider` VARCHAR(45) NOT NULL,
  `numMembros` INT NOT NULL,
  `raca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lider`),
  INDEX `fk_Alianca_Character1_idx` (`lider` ASC) VISIBLE,
  CONSTRAINT `fk_Alianca_Character1`
    FOREIGN KEY (`lider`)
    REFERENCES `batalha`.`Person` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `batalha`.`Allys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batalha`.`Allys` ;

CREATE TABLE IF NOT EXISTS `batalha`.`Allys` (
  `Alianca_lider` VARCHAR(45) NOT NULL,
  `Alianca_lider1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Alianca_lider`, `Alianca_lider1`),
  INDEX `fk_Alianca_has_Alianca_Alianca2_idx` (`Alianca_lider1` ASC) VISIBLE,
  INDEX `fk_Alianca_has_Alianca_Alianca1_idx` (`Alianca_lider` ASC) VISIBLE,
  CONSTRAINT `fk_Alianca_has_Alianca_Alianca1`
    FOREIGN KEY (`Alianca_lider`)
    REFERENCES `batalha`.`Alliance` (`lider`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Alianca_has_Alianca_Alianca2`
    FOREIGN KEY (`Alianca_lider1`)
    REFERENCES `batalha`.`Alliance` (`lider`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
